# Setup
title: Revist의 사소한 공간
description: 사소한 순간의 깨달음을 모아,<br>꽃이 피는 첫걸음을 내딛는 곳.
url: https://revist8956.github.io/
avatar: /avatar.jpeg
paginate: 10
permalink: none
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-category

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
instagram:
  username: revist8956
  card: summary
logo: logo.png
social:
  name: revist8956
  links:
    - https://instagram.com/revist8956
    - https://github.com/revist8956
google_site_verification: xxxxx
lang: 'en-uk'

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0


disqus: https-revist8956-github-io

# Specify the author for blog posts
revist8956:
  username: revist8956
  name: Ahn Jun Seong
  url: https://github.com/revist8956
  email: lljs1113@naver.com

# Travis-CI Settings
safe: False
lsi: False
destination: ./output/